/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package slaintehealth;

import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;

/**
 *
 * @author it120
 */
public class BuyPolicy extends javax.swing.JDialog  {

    /**
     * Creates new form BuyPolicy
     */
    
        public BuyPolicy(java.awt.Frame parent, boolean modal, Customer cust, Policy pol) {
        super(parent, modal);
        initComponents();
        
        showCustomer(cust,pol);
    }
    
    public BuyPolicy(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        firstNameLbl = new javax.swing.JLabel();
        surnameLbl = new javax.swing.JLabel();
        genderLbl = new javax.swing.JLabel();
        ageLbl = new javax.swing.JLabel();
        healthLabel = new javax.swing.JLabel();
        ifOtherLabel = new javax.swing.JLabel();
        smokerLabel = new javax.swing.JLabel();
        policyLabel = new javax.swing.JLabel();
        hospitalLabel = new javax.swing.JLabel();
        dayToDayLabel = new javax.swing.JLabel();
        idNoLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        firstNameInfo = new javax.swing.JLabel();
        surNameInfo = new javax.swing.JLabel();
        genderInfo = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        healthInfo = new javax.swing.JLabel();
        ifOtherInfo = new javax.swing.JLabel();
        smokerInfo = new javax.swing.JLabel();
        policyTypeInfo = new javax.swing.JLabel();
        hospitalInfo = new javax.swing.JLabel();
        dailyInfo = new javax.swing.JLabel();
        idNoInfo = new javax.swing.JLabel();
        totalInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buy Policy Overview");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)));
        jPanel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setText("Policy Details");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));

        firstNameLbl.setText("First Name:");

        surnameLbl.setText("Surname:");

        genderLbl.setText("Gender:");

        ageLbl.setText("Age:");

        healthLabel.setText("Existing Health Conditions:");

        ifOtherLabel.setText("If Other:");

        smokerLabel.setText("Smoker:");

        policyLabel.setText("Policy Type:");

        hospitalLabel.setText("Hospital Cover:");

        dayToDayLabel.setText("Day to Day Expenses:");

        idNoLabel.setText("ID No:");

        totalLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalLabel.setText("Total:");

        firstNameInfo.setText("jLabel2");

        surNameInfo.setText("jLabel3");

        genderInfo.setText("jLabel4");

        age.setText("jLabel5");

        healthInfo.setText("jLabel6");

        ifOtherInfo.setText("jLabel7");

        smokerInfo.setText("jLabel8");

        policyTypeInfo.setText("jLabel9");

        hospitalInfo.setText("jLabel10");

        dailyInfo.setText("jLabel11");

        idNoInfo.setText("jLabel12");

        totalInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalInfo.setText("jLabel13");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameLbl)
                            .addComponent(surnameLbl)
                            .addComponent(genderLbl)
                            .addComponent(ageLbl)
                            .addComponent(healthLabel)
                            .addComponent(ifOtherLabel)
                            .addComponent(smokerLabel)
                            .addComponent(policyLabel)
                            .addComponent(hospitalLabel)
                            .addComponent(dayToDayLabel)
                            .addComponent(idNoLabel)
                            .addComponent(totalLabel))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalInfo)
                            .addComponent(idNoInfo)
                            .addComponent(dailyInfo)
                            .addComponent(hospitalInfo)
                            .addComponent(policyTypeInfo)
                            .addComponent(smokerInfo)
                            .addComponent(ifOtherInfo)
                            .addComponent(healthInfo)
                            .addComponent(age)
                            .addComponent(genderInfo)
                            .addComponent(surNameInfo)
                            .addComponent(firstNameInfo)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLbl)
                    .addComponent(firstNameInfo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(surnameLbl)
                    .addComponent(surNameInfo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLbl)
                    .addComponent(genderInfo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLbl)
                    .addComponent(age))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(healthLabel)
                    .addComponent(healthInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ifOtherLabel)
                    .addComponent(ifOtherInfo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smokerLabel)
                    .addComponent(smokerInfo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(policyLabel)
                    .addComponent(policyTypeInfo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hospitalLabel)
                    .addComponent(hospitalInfo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dayToDayLabel)
                    .addComponent(dailyInfo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idNoLabel)
                    .addComponent(idNoInfo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalLabel)
                    .addComponent(totalInfo))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuyPolicy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuyPolicy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuyPolicy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuyPolicy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BuyPolicy dialog = new BuyPolicy(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel age;
    private javax.swing.JLabel ageLbl;
    private javax.swing.JLabel dailyInfo;
    private javax.swing.JLabel dayToDayLabel;
    private javax.swing.JLabel firstNameInfo;
    private javax.swing.JLabel firstNameLbl;
    private javax.swing.JLabel genderInfo;
    private javax.swing.JLabel genderLbl;
    private javax.swing.JLabel healthInfo;
    private javax.swing.JLabel healthLabel;
    private javax.swing.JLabel hospitalInfo;
    private javax.swing.JLabel hospitalLabel;
    private javax.swing.JLabel idNoInfo;
    private javax.swing.JLabel idNoLabel;
    private javax.swing.JLabel ifOtherInfo;
    private javax.swing.JLabel ifOtherLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel policyLabel;
    private javax.swing.JLabel policyTypeInfo;
    private javax.swing.JLabel smokerInfo;
    private javax.swing.JLabel smokerLabel;
    private javax.swing.JLabel surNameInfo;
    private javax.swing.JLabel surnameLbl;
    private javax.swing.JLabel totalInfo;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables

    private void showCustomer (Customer cust, Policy pol) {
        
        firstNameInfo.setText(cust.getFirstName());
        surNameInfo.setText(cust.getSurname());
        genderInfo.setText(cust.getGender());
        age.setText(cust.getAge());
        smokerInfo.setText(String.valueOf(cust.getSmoker()));
        ifOtherInfo.setText(cust.getIfOther());
        
        //create a new string variable
        String health = "";
        //initialise 
        //create a new arraylist 
        ArrayList health2 = new ArrayList();
        //store the contents of healthconditions in
        //the new array list
        health2 = cust.getHealthConditions();
        
        //for loop
        //iterate through the contents of the new array list
        //use .size() as termination condition
        for(int i = 0; i < health2.size(); i++ ){
        //concatenate the contents of the arraylist
        //to the string on each iteration
        //.get(i) 
            health += health2.get(i) + " , ";
        }  
        //pass the string variable to the label 
        healthInfo.setText(health);
        policyTypeInfo.setText(pol.getPolicyType());
        hospitalInfo.setText(pol.getHospitalCover());
        dailyInfo.setText(pol.getDailyExpenses());
        idNoInfo.setText(Integer.toString(pol.getPolicyId()));
        totalInfo.setText(Float.toString(pol.getTotal()));
        
        NumberFormat currencyFormat = NumberFormat.getCurrencyInstance(Locale.FRANCE);
        totalInfo.setText(currencyFormat.format(Math.round(pol.getTotal())));
  
    }
}
